using UnityEngine;
using UnityEngine.InputSystem;

/// Movement states of the character.
public enum MoveState
{
    Ground,
    Falling,
    AirDash,
    WallRun,
    Stun
}

[RequireComponent(typeof(CharacterController))]
public class ParkourController : MonoBehaviour
{
    [Header("References")]
    [Tooltip("CharacterController on this object.")]
    public CharacterController cc;

    [Tooltip("Camera rig used for camera-relative directions.")]
    public CameraRigController camRig;

    [Header("Input")]
    [Tooltip("Input actions wrapper generated by the Input System.")]
    public PlayerControls input;

    // Raw input state
    Vector2 moveInput;           // left stick
    Vector2 lookInput;           // right stick / mouse
    bool   dashHeld;             // dash button currently held
    bool   dashPress;            // dash pressed this frame
    bool   jump;                 // jump pressed this frame

    [Header("Ground Movement")]
    [Tooltip("Ground walk speed.")]
    public float walkSpeed = 6f;

    [Tooltip("Jump impulse (vertical speed).")]
    public float jumpImpulse = 8f;

    [Tooltip("Allow a double jump while falling.")]
    public bool allowDoubleJump = true;

    [Tooltip("Double jump impulse (vertical speed).")]
    public float doubleJumpImpulse = 7f;

    [Header("Gravity")]
    [Tooltip("Gravity acceleration (negative).")]
    public float gravity = -20f;

    [Header("Air Steering")]
    [Tooltip("Base maximum turn rate (deg/s).")]
    public float steerOmega0 = 360f;

    [Tooltip("Turn-rate falloff with speed (bigger = stronger).")]
    public float steerOmegaK = 0.08f;

    [Tooltip("Minimum turn rate (deg/s).")]
    public float steerOmegaMin = 60f;

    [Tooltip("Horizontal damping factor in air.")]
    public float airFriction = 1.5f;

    [Header("Air Dash")]
    [Tooltip("Stick dead zone for dash direction.")]
    public float dashStickDead = 0.15f;

    [Tooltip("Minimum speed treated as dash (cosmetic threshold).")]
    public float dashMinSpeed = 0.1f;

    [Tooltip("Base energy drain per second while dashing.")]
    public float dashDrainBase = 22f;

    [Tooltip("Extra drain per unit dash speed.")]
    public float dashDrainSpeedCoeff = 0.04f;

    [Header("Dash Camera Follow")]
    [Tooltip("Max camera yaw follow speed while dashing (deg/s).")]
    public float dashCamFollowMaxDegPerSec = 150f;

    [Header("Energy")]
    [Tooltip("Maximum energy.")]
    public float energyMax = 100f;

    [Tooltip("Energy regen per second on ground.")]
    public float energyRegen = 8f;

    [Tooltip("Energy regen per second while wall-running.")]
    public float wallRunRegen = 12f;

    [Tooltip("Minimal energy required to start a dash.")]
    public float minEnergyToDash = 5f;

    [Tooltip("Energy threshold after depletion until dash is re-armed.")]
    public float rearmEnergyAfterDeplete = 50f;

    bool needRearm = false; // true once energy hits 0 during dash

    [Header("Dash Bonus Speed")]
    [Tooltip("Base minimum burst speed when starting a dash.")]
    public float burstSpeedBase = 20f;

    [Tooltip("Max bonus added to current speed when starting a dash.")]
    public float bonusMax = 10f;

    [Tooltip("Exponential decay of bonus with current speed.")]
    public float bonusK = 0.08f;

    [Tooltip("Minimum bonus at very high speed.")]
    public float bonusMin = 0f;

    [Header("Wall Run")]
    [Tooltip("Gravity while wall-running (negative, small magnitude).")]
    public float wallRunGravity = -4f;

    [Tooltip("Tangential speed decay while wall-running.")]
    public float wallRunSpeedDecay = 2.0f;

    [Tooltip("Minimum horizontal speed to keep wall-running.")]
    public float minWallRunSpeed = 1.0f;

    [Tooltip("Max |dot(normal, up)| to still treat as wall (0.9 ≈ exclude only almost-up surfaces).")]
    public float wallMaxUpDot = 0.9f;

    [Tooltip("Distance for wall detection along velocity direction.")]
    public float wallDetectDistance = 1.0f;

    [Tooltip("Layer mask used for wall detection raycasts.")]
    public LayerMask wallMask = ~0;

    [Tooltip("Only colliders with this tag are valid wall-run surfaces.")]
    public string wallRunTag = "Wallrun";

    [Header("Wall Run Robustness")]
    [Tooltip("Minimal time a wall-run must last to be considered valid (seconds).")]
    public float minWallRunTimeBeforeDrop = 0.12f;

    float   wallRunTimer;
    Vector3 preWallRunVelocity;

    [Header("Dash Collision / Stun")]
    [Tooltip("Extra distance for dash collision check.")]
    public float dashCollisionPadding = 0.1f;

    [Tooltip("Stun time when hitting wall during dash.")]
    public float stunTime = 1.0f;

    [Header("Debug")]
    [Tooltip("Log state and velocity every frame.")]
    public bool logStateEachFrame = false;

    [Tooltip("Log wall-run enter/exit and dash events.")]
    public bool logWallEvents = true;

    // Runtime state
    public MoveState state = MoveState.Ground;
    Vector3 velocity;
    float   energy;
    bool    hasDoubleJump;
    bool    canWallRun = true;
    Vector3 wallNormal;
    Vector3 wallTangent;
    float   stunTimer;

    void Awake()
    {
        if (!cc) cc = GetComponent<CharacterController>();
        input = new PlayerControls();
        energy = energyMax;
        UpdateEnergyUI();
    }

    void OnEnable()
    {
        input.Enable();

        input.Gameplay.Move.performed += ctx => moveInput = ctx.ReadValue<Vector2>();
        input.Gameplay.Move.canceled  += _   => moveInput = Vector2.zero;

        input.Gameplay.Look.performed += ctx => lookInput = ctx.ReadValue<Vector2>();
        input.Gameplay.Look.canceled  += _   => lookInput = Vector2.zero;

        input.Gameplay.Dash.started   += _   => { dashHeld = true;  dashPress = true; };
        input.Gameplay.Dash.performed += _   => { dashHeld = true; };
        input.Gameplay.Dash.canceled  += _   => { dashHeld = false; };

        input.Gameplay.Jump.started   += _   => { jump = true; };
    }

    void OnDisable()
    {
        input.Disable();
    }

    void Update()
    {
        if (camRig != null)
            camRig.ManualUpdate(lookInput.x, lookInput.y);

        switch (state)
        {
            case MoveState.Ground:   TickGround();   break;
            case MoveState.Falling:  TickFalling();  break;
            case MoveState.AirDash:  TickAirDash();  break;
            case MoveState.WallRun:  TickWallRun();  break;
            case MoveState.Stun:     TickStun();     break;
        }

        if (logStateEachFrame)
        {
            Debug.Log($"[Parkour] state={state}, vel={velocity}, grounded={cc.isGrounded}, canWallRun={canWallRun}, energy={energy:F1}");
        }

        dashPress = false;
        jump = false;
    }

    // --------- State ticks ---------

    void TickGround()
    {
        MoveOnGround();

        if (dashHeld && CanStartDash())
        {
            StartDash();
            return;
        }

        RegenerateEnergy(energyRegen);

        if (!cc.isGrounded)
        {
            state = MoveState.Falling;
            hasDoubleJump = allowDoubleJump;
            canWallRun = true;
        }
    }

    void TickFalling()
    {
        if (dashHeld && CanStartDash())
        {
            StartDash();
            return;
        }

        DoAirMovement();

        if (jump && hasDoubleJump)
        {
            hasDoubleJump = false;
            velocity.y = doubleJumpImpulse;
        }

        // Falling: as soon as we touch a valid wall, we try to wall-run
        if (canWallRun && DetectWall(out Vector3 n))
        {
            if (TryEnterWallRun(n))
                return;
        }

        if (cc.isGrounded)
        {
            velocity.y = -2f;
            state = MoveState.Ground;
            canWallRun = true;
            camRig?.SetDefaultMode();
        }

        RegenerateEnergy(energyRegen * 2f);
    }

    void TickAirDash()
    {
        if (!dashHeld)
        {
            state = MoveState.Falling;
            return;
        }

        float speed = velocity.magnitude;
        if (speed > dashMinSpeed)
        {
            Vector3 curDir    = velocity.normalized;
            Vector3 targetDir = DashDirFromStick(moveInput);

            float omegaMaxDeg = Mathf.Max(steerOmegaMin, steerOmega0 / (1f + steerOmegaK * speed));
            float maxRad      = Mathf.Deg2Rad * omegaMaxDeg * Time.deltaTime;

            Vector3 newDir = Vector3.RotateTowards(curDir, targetDir, maxRad, 0f);
            velocity = newDir * speed;

            if (camRig != null)
            {
                Vector3 horizDir = new Vector3(newDir.x, 0f, newDir.z);
                if (horizDir.sqrMagnitude > 1e-6f)
                {
                    horizDir.Normalize();
                    Vector3 camFwd = camRig.FlatForward();
                    float angleDiff = Mathf.Abs(Vector3.SignedAngle(camFwd, horizDir, Vector3.up));

                    float clamped = Mathf.Min(angleDiff, 90f);
                    float factor  = clamped / 90f;

                    float maxDelta = dashCamFollowMaxDegPerSec * factor * Time.deltaTime;
                    camRig.NudgeYawTowardsDirection(horizDir, maxDelta);
                }
            }
        }

        Vector3 step = velocity * Time.deltaTime;

        if (CapsuleCastAhead(step, out RaycastHit hit))
        {
            EnterStun(hit.normal);
            return;
        }

        cc.Move(step);

        float drain = dashDrainBase * (1f + dashDrainSpeedCoeff * speed) * Time.deltaTime;
        energy = Mathf.Max(0f, energy - drain);
        UpdateEnergyUI();


        if (energy <= 0f)
        {
            energy = 0f;
            needRearm = true;
            state = MoveState.Falling;
        }
    }

    void TickWallRun()
    {
        wallRunTimer += Time.deltaTime;

        if (dashHeld && CanStartDash())
        {
            StartDash();
            return;
        }

        if (!IsStillOnWall())
        {
            if (logWallEvents) Debug.Log("[Parkour] Exit WallRun: lost wall.");
            ExitWallRunToFalling();
            return;
        }

        Vector3 tangential = Vector3.ProjectOnPlane(velocity, wallNormal);
        if (tangential.sqrMagnitude > 1e-6f)
        {
            Vector3 tDir = tangential.normalized;
            float tSpeed = tangential.magnitude;
            tSpeed = Mathf.Max(0f, tSpeed - wallRunSpeedDecay * Time.deltaTime);
            tangential = tDir * tSpeed;
        }
        else
        {
            tangential = Vector3.zero;
        }

        velocity.x = tangential.x;
        velocity.z = tangential.z;

        velocity.y += wallRunGravity * Time.deltaTime;
        cc.Move(velocity * Time.deltaTime);

        Vector3 horizNow = new Vector3(velocity.x, 0f, velocity.z);
        float horizSpeed = horizNow.magnitude;

        if (jump)
        {
            Vector3 away = wallNormal + Vector3.up;
            away.Normalize();
            velocity = away * walkSpeed;
            velocity.y = jumpImpulse;

            if (logWallEvents) Debug.Log("[Parkour] Exit WallRun: jump off wall.");
            ExitWallRunToFalling();
            return;
        }

        if (cc.isGrounded || horizSpeed < minWallRunSpeed)
        {
            if (logWallEvents)
                Debug.Log($"[Parkour] Exit WallRun: grounded={cc.isGrounded}, horizSpeed={horizSpeed:F2}");
            ExitWallRunToFalling();
            return;
        }

        RegenerateEnergy(wallRunRegen);
    }

    void TickStun()
    {
        stunTimer -= Time.deltaTime;

        velocity.y += gravity * Time.deltaTime;
        cc.Move(velocity * Time.deltaTime);

        if (stunTimer <= 0f)
        {
            if (cc.isGrounded)
            {
                velocity = new Vector3(0f, -2f, 0f);
                state = MoveState.Ground;
                canWallRun = true;
                camRig?.SetDefaultMode();
            }
            else
            {
                state = MoveState.Falling;
            }
        }

        RegenerateEnergy(energyRegen);
    }

    // --------- Actions ---------

    void MoveOnGround()
    {
        Vector3 fwd   = camRig ? camRig.FlatForward() : transform.forward;
        Vector3 right = camRig ? camRig.FlatRight()   : transform.right;

        Vector3 dir   = (fwd * moveInput.y + right * moveInput.x).normalized;
        Vector3 horiz = dir * walkSpeed;
        velocity.x = horiz.x;
        velocity.z = horiz.z;

        if (cc.isGrounded)
        {
            velocity.y = -2f;
            if (jump)
            {
                velocity.y = jumpImpulse;
                hasDoubleJump = allowDoubleJump;
                state = MoveState.Falling;
                canWallRun = true;
            }
        }
        else
        {
            velocity.y += gravity * Time.deltaTime;
            state = MoveState.Falling;
            hasDoubleJump = allowDoubleJump;
            canWallRun = true;
        }

        cc.Move(velocity * Time.deltaTime);
    }

    void DoAirMovement()
    {
        Vector3 horiz = new Vector3(velocity.x, 0f, velocity.z);
        if (horiz.sqrMagnitude > 0.0001f)
        {
            float damp = Mathf.Exp(-airFriction * Time.deltaTime);
            horiz *= damp;

            Vector3 fwd   = camRig ? camRig.FlatForward() : transform.forward;
            Vector3 right = camRig ? camRig.FlatRight()   : transform.right;
            Vector3 desiredDir = (fwd * moveInput.y + right * moveInput.x).normalized;

            if (desiredDir.sqrMagnitude > 0.001f)
            {
                float speed = horiz.magnitude;
                Vector3 curDir = horiz.normalized;
                float omegaMaxDeg = Mathf.Max(steerOmegaMin, steerOmega0 / (1f + steerOmegaK * speed));
                float maxRad = Mathf.Deg2Rad * omegaMaxDeg * Time.deltaTime;
                Vector3 newDir = Vector3.RotateTowards(curDir, desiredDir, maxRad, 0f);
                horiz = newDir * speed;
            }
        }

        velocity.x = horiz.x;
        velocity.z = horiz.z;

        velocity.y += gravity * Time.deltaTime;
        cc.Move(velocity * Time.deltaTime);
    }

    void StartDash()
    {
        bool fromWallRun = (state == MoveState.WallRun);

        float currentSpeed = velocity.magnitude;
        float burst        = DashBurst(currentSpeed);
        Vector3 dir        = DashDirFromStick(moveInput);

        velocity = dir * burst;

        state = MoveState.AirDash;
        canWallRun = true;

        if (fromWallRun && camRig != null)
            camRig.SetDefaultMode();

        if (logWallEvents)
            Debug.Log($"[Parkour] StartDash: fromWallRun={fromWallRun}, speed={currentSpeed:F2} -> burst={burst:F2}, dir={dir}");
    }

    bool TryEnterWallRun(Vector3 n)
    {
        float upDot = Mathf.Abs(Vector3.Dot(n, Vector3.up));
        if (upDot > wallMaxUpDot)
            return false;

        float toward = -Vector3.Dot(velocity.normalized, n.normalized); // >0 means moving into wall
        if (toward <= 0f)
            return false;

        Vector3 horiz = new Vector3(velocity.x, 0f, velocity.z);
        if (horiz.sqrMagnitude < 0.01f)
            horiz = transform.forward;

        if (logWallEvents)
            Debug.Log($"[Parkour] TryEnterWallRun: horiz={horiz}, n={n}, toward={toward:F2}");

        EnterWallRun(n, horiz);
        return true;
    }

    void EnterWallRun(Vector3 n, Vector3 horiz)
    {
        preWallRunVelocity = velocity;
        wallRunTimer = 0f;

        wallNormal = n;

        Vector3 tangent = Vector3.ProjectOnPlane(horiz, wallNormal);
        if (tangent.sqrMagnitude < 0.0001f)
            tangent = Vector3.Cross(wallNormal, Vector3.up);
        tangent.Normalize();

        wallTangent = tangent;

        float speed = horiz.magnitude;
        velocity = wallTangent * Mathf.Max(speed, minWallRunSpeed);

        Vector3 horizDir = horiz.normalized;
        Vector3 leftDir  = Vector3.Cross(Vector3.up, horizDir);
        float sideDot    = Vector3.Dot(wallNormal, leftDir);
        bool wallIsRight = sideDot < 0f;

        camRig?.SetWallRunMode(wallTangent, wallIsRight);

        state = MoveState.WallRun;
        canWallRun = false;

        energy = Mathf.Min(energyMax, energy + 30f);
        UpdateEnergyUI();


        if (logWallEvents)
            Debug.Log($"[Parkour] EnterWallRun OK: wallIsRight={wallIsRight}, tangent={wallTangent}, speed={speed:F2}, sideDot={sideDot:F3}");
    }

    void ExitWallRunToFalling()
    {
        if (wallRunTimer < minWallRunTimeBeforeDrop)
        {
            velocity = preWallRunVelocity;
        }

        state = MoveState.Falling;
        camRig?.SetDefaultMode();
        canWallRun = true;
    }

    void EnterStun(Vector3 hitNormal)
    {
        state = MoveState.Stun;
        stunTimer = stunTime;

        Vector3 away = hitNormal + Vector3.up * 0.3f;
        away.Normalize();
        velocity = away * walkSpeed * 0.5f;

        camRig?.SetDefaultMode();
        canWallRun = false;

        if (logWallEvents)
            Debug.Log($"[Parkour] EnterStun: hitNormal={hitNormal}");
    }

    // --------- Utility ---------

    bool CanStartDash()
    {
        float gate = needRearm ? rearmEnergyAfterDeplete : minEnergyToDash;
        return energy >= gate;
    }

    void RegenerateEnergy(float rate)
    {
        if (state == MoveState.AirDash)
            return;

        energy = Mathf.Min(energyMax, energy + rate * Time.deltaTime);
        if (needRearm && energy >= rearmEnergyAfterDeplete)
            needRearm = false;

        UpdateEnergyUI();
    }

    float DashBurst(float currentSpeed)
    {
        return Mathf.Max(burstSpeedBase, currentSpeed + Bonus(currentSpeed));
    }

    float Bonus(float v)
    {
        v = Mathf.Max(0f, v);
        return bonusMax * Mathf.Exp(-bonusK * v) + bonusMin;
    }

    Vector3 DashDirFromStick(Vector2 stick)
    {
        Vector3 F = camRig ? camRig.Forward3D() : transform.forward;
        Vector3 R = (camRig != null && camRig.cam != null) ? camRig.cam.transform.right : transform.right;

        if (stick.sqrMagnitude < dashStickDead * dashStickDead)
            return F.normalized;

        Vector3 dir = F * stick.y + R * stick.x;
        if (dir.sqrMagnitude < 1e-6f)
            return F.normalized;

        return dir.normalized;
    }


    bool DetectWall(out Vector3 normal)
    {
        normal = Vector3.zero;

        Vector3 origin = transform.position + Vector3.up * (cc.height * 0.5f);
        Vector3 dir    = velocity.sqrMagnitude > 0.0001f ? velocity.normalized : transform.forward;

        if (Physics.Raycast(origin, dir, out RaycastHit hit, wallDetectDistance, wallMask))
        {
            if (!string.IsNullOrEmpty(wallRunTag) && !hit.collider.CompareTag(wallRunTag))
                return false;

            Vector3 n = hit.normal;
            float upDot = Mathf.Abs(Vector3.Dot(n, Vector3.up));
            if (upDot > wallMaxUpDot)
                return false;

            normal = n;
            return true;
        }

        return false;
    }

    bool IsStillOnWall()
    {
        Vector3 origin = transform.position + Vector3.up * (cc.height * 0.5f);
        float   maxDist = wallDetectDistance + 0.1f;
        Vector3 dir = -wallNormal;

        if (Physics.Raycast(origin, dir, out RaycastHit hit, maxDist, wallMask))
        {
            if (!string.IsNullOrEmpty(wallRunTag) && !hit.collider.CompareTag(wallRunTag))
                return false;

            Vector3 n = hit.normal;
            float upDot = Mathf.Abs(Vector3.Dot(n, Vector3.up));
            if (upDot > wallMaxUpDot)
                return false;

            return true;
        }

        return false;
    }

    bool CapsuleCastAhead(Vector3 step, out RaycastHit hit)
    {
        Vector3 p1 = transform.position + Vector3.up * cc.radius;
        Vector3 p2 = transform.position + Vector3.up * (cc.height - cc.radius);
        float dist = step.magnitude + dashCollisionPadding;
        Vector3 dir = dist > 0.0001f ? step.normalized : transform.forward;

        return Physics.CapsuleCast(p1, p2, cc.radius * 0.95f, dir, out hit, dist, wallMask);
    }
    
    void UpdateEnergyUI()
    {
        UIHud.Instance?.SetEnergy(energy / energyMax);
    }

}
